### ISSUE TITLE
Color is not the same that EmbedColor describes

### ISSUE THREAD

**Issue by DiFFoZ** [ShimmyMySherbet/DiscordWebhooks#1]
`EmbedColor.OrangeRed`
![image](https://user-images.githubusercontent.com/48765566/147293097-d5f3e752-0ae3-4294-a470-c0c5c0912204.png)

and etc..

**Comment by ShimmyMySherbet** [comment]
Odd, the colors themselves are from a color code list, so it might be worth going through and checking them.
